# Generated by Django 5.2.6 on 2025-12-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_resource_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='is_active',
        ),
    ]
