# Generated by Django 5.2.6 on 2025-12-12 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_area_carrera_profile_area_profile_carrera'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources_used', to='api.reservation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage', to='api.resource')),
            ],
        ),
    ]
